//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.34014
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OE110Prozessdatenbank.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OE110Prozessdatenbank.Properties.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Es kann kein weiterer Versuch durchgeführt werden, da der Vorgang bereits beendet wurde! ähnelt.
        /// </summary>
        internal static string e_cannnotDoNextTry {
            get {
                return ResourceManager.GetString("e_cannnotDoNextTry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Der Vorgang ist bereits beendet worden! ähnelt.
        /// </summary>
        internal static string e_cannotCancelProcess {
            get {
                return ResourceManager.GetString("e_cannotCancelProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Der Vorgang kann nicht übersprungen werden, da dem diesem kein Projekt oder keine Fragestellung zugeordnet ist! ähnelt.
        /// </summary>
        internal static string e_NoProjectNoIssue {
            get {
                return ResourceManager.GetString("e_NoProjectNoIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Es wurde kein Listenelement ausgewählt! ähnelt.
        /// </summary>
        internal static string e_NoSelectedListElement {
            get {
                return ResourceManager.GetString("e_NoSelectedListElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die eingegebene Vorgangsnummer ist nicht vorhanden! ähnelt.
        /// </summary>
        internal static string e_UnknownReference {
            get {
                return ResourceManager.GetString("e_UnknownReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Achtung! Die Änderungen werden erst durch klicken auf &apos;speichern&apos; übernommen! ähnelt.
        /// </summary>
        internal static string n_SaveGlassParameters {
            get {
                return ResourceManager.GetString("n_SaveGlassParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Das Werkstück befindet sich aktuell nicht im Durchlauf! ähnelt.
        /// </summary>
        internal static string n_WorkpieceNotInUse {
            get {
                return ResourceManager.GetString("n_WorkpieceNotInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Soll der Vorgnag wirklich abgebrochen werden? ähnelt.
        /// </summary>
        internal static string q_CancelReference {
            get {
                return ResourceManager.GetString("q_CancelReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Soll die Fragestellung wirklich geändert werden? ähnelt.
        /// </summary>
        internal static string q_editIssue {
            get {
                return ResourceManager.GetString("q_editIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Soll das Projekt wirklich geändert werden? ähnelt.
        /// </summary>
        internal static string q_editProject {
            get {
                return ResourceManager.GetString("q_editProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Prozessdaten jetzt importieren? Spätere Änderungen sind nur für einzelene Prozesse möglich! ähnelt.
        /// </summary>
        internal static string q_importToshiba {
            get {
                return ResourceManager.GetString("q_importToshiba", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Soll das Werkstück wirklich für einen weiteren Versuch freigegeben werden? ähnelt.
        /// </summary>
        internal static string q_NextTry {
            get {
                return ResourceManager.GetString("q_NextTry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Soll das Material wirklich gelöscht werden? ähnelt.
        /// </summary>
        internal static string q_removeMaterial {
            get {
                return ResourceManager.GetString("q_removeMaterial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Soll das Werkstück  wirklich in den Prozesszustand &apos;Beschichtet&apos; versetzt werden? ähnelt.
        /// </summary>
        internal static string q_skipWorkpieceCoating {
            get {
                return ResourceManager.GetString("q_skipWorkpieceCoating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Soll das Werkstück  wirklich in den Prozesszustand &apos;Bearbeitet&apos; versetzt werden? ähnelt.
        /// </summary>
        internal static string q_skipWorkpieceGrinding {
            get {
                return ResourceManager.GetString("q_skipWorkpieceGrinding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Soll das Werkstück  wirklich in den Prozesszustand &apos;Versuch durchgeführt&apos; versetzt werden? ähnelt.
        /// </summary>
        internal static string q_skipWorkpieceProc1 {
            get {
                return ResourceManager.GetString("q_skipWorkpieceProc1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Soll der Vorgang wirklich beendet werden? ähnelt.
        /// </summary>
        internal static string q_TerminateReference {
            get {
                return ResourceManager.GetString("q_TerminateReference", resourceCulture);
            }
        }
    }
}
